name: Publish Comfy Node

on:
  push:
    branches: [ "main" ]
    paths:
      - "pyproject.toml"
      - "nodes.py"
      - "**/*.py"
      - ".github/workflows/publish_node.yml"
  workflow_dispatch:

jobs:
  publish:
    runs-on: ubuntu-latest

    permissions:
      contents: read

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Install comfy-cli
        run: |
          python -m pip install --upgrade pip
          pip install "comfy-cli>=0.9.0"

      - name: Validate node
        run: |
          comfy node validate

      - name: Publish node
        env:
          COMFY_REGISTRY_ACCESS_TOKEN: ${{ secrets.REGISTRY_ACCESS_TOKEN }}
        run: |
          if [ -z "${COMFY_REGISTRY_ACCESS_TOKEN}" ]; then
            echo "Missing secret: REGISTRY_ACCESS_TOKEN"; exit 1;
          fi
          # 大多数版本的 comfy-cli 会从 COMFY_REGISTRY_ACCESS_TOKEN 读取 Token
          # 如果你的版本需要从标准输入读取，可以改为：
          #   echo "${COMFY_REGISTRY_ACCESS_TOKEN}" | comfy node publish
          comfy node publish
